services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fullcycle
  node:
    container_name: node
    image: node:lts
    restart: always
    stdin_open: true
    tty: true
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run start"
    ports:
      - "3333:3333"
    volumes:
      - ./:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fullcycle
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      node:
        condition: service_started
    networks:
      - fullcycle

networks:
  fullcycle:
    name: fullcycle
    driver: bridge